// SPDX-License-Identifier: MIT 
// Oracle.sol
pragma solidity ^0.8.0;

contract SimpleOracle {
    address public owner;
    mapping(uint256 => bool) map; // uint256 is the order ID (generated by us only)

    event DataUpdated(uint256 orderID, bool status);

    constructor() {
        owner = msg.sender;
    }

    function updateData(uint256 orderID, bool status) public {
        require(msg.sender == owner, "Only oracle updater can post data");
        map[orderID] = status;
        emit DataUpdated(orderID, status);
    }

    function getData(uint256 orderID) external view returns (bool) {
        return map[orderID];
    }
}

